rail:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  yaw_position_controller:
    type: effort_controllers/JointPositionController
    joint: yaw
    pid: {p: 100.0, i: 1, d: 10.0}
  pitch_position_controller:
    type: effort_controllers/JointPositionController
    joint: pitch
    pid: {p: 100.0, i: 100, d: 10.0}
